### ISSUE TITLE
In most frames, Bbox cover all frame

### ISSUE THREAD

**Issue by aliaminibagh** [Abonia1/YOLOv8-Fire-and-Smoke-Detection#1]
After testing the model on the frames of video or images, it was observed that most of the bounding boxes cover most of the width and height of the frame. In other words, the size of the output bounding box is too big.
Is this because of the YOLO 8 algorithm itself or not?

![Capture](https://user-images.githubusercontent.com/59368585/219391661-3bd39a54-1b21-4644-b3d8-8b5a1e1a89ad.JPG)

**Comment by Abonia1** [comment]
Hello @aliaminibagh 
It seems promising and good as if the model detect smoke around entire frame.

But I see here  the  fire in the left bottom corner is not detected  well as we should augment the data in order to fine-tune the scenerio where we can find smoke and fire in frame.

**Comment by aliaminibagh** [comment]
> Hello @aliaminibagh It seems promising and good as if the model detect smoke around entire frame.
> 
> But I see here the fire in the left bottom corner is not detected well as we should augment the data in order to fine-tune the scenerio where we can find smoke and fire in frame.

thanks alot
